-- Generated by Envision Gui2Lua, VER-1, 0-18.

local Instances = {
	kitlibrload = Instance.new("ScreenGui"),
	Frame = Instance.new("Frame"),
	UICorner = Instance.new("UICorner"),
	loadedtext = Instance.new("TextLabel"),
	title = Instance.new("TextLabel"),
	description = Instance.new("TextLabel"),
	UIGradient = Instance.new("UIGradient"),
}

Instances.kitlibrload.Name = "kitlibrload"
Instances.kitlibrload.Parent = game.CoreGui

Instances.Frame.Name = "Frame"
Instances.Frame.Parent = Instances.kitlibrload
Instances.Frame.Size = UDim2.new(0, 392, 0, 306)
Instances.Frame.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.Frame.Position = UDim2.new(0.356999993, 0, 0.310000002, 0)
Instances.Frame.BorderSizePixel = 0
Instances.Frame.BackgroundColor3 = Color3.fromRGB(188, 188, 188)

Instances.UICorner.Name = "UICorner"
Instances.UICorner.Parent = Instances.Frame
Instances.UICorner.CornerRadius = UDim.new(0, 6)

Instances.loadedtext.Name = "loadedtext"
Instances.loadedtext.Parent = Instances.Frame
Instances.loadedtext.Size = UDim2.new(0, 392, 0, 21)
Instances.loadedtext.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.loadedtext.BackgroundTransparency = 1
Instances.loadedtext.Position = UDim2.new(0, 0, 0.46405229, 0)
Instances.loadedtext.BorderSizePixel = 0
Instances.loadedtext.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.loadedtext.TextColor3 = Color3.fromRGB(255, 255, 255)
Instances.loadedtext.Text = "loaded"
Instances.loadedtext.TextSize = 16
Instances.loadedtext.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Bold, Enum.FontStyle.Normal)

Instances.title.Name = "title"
Instances.title.Parent = Instances.Frame
Instances.title.Size = UDim2.new(0, 392, 0, 21)
Instances.title.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.title.BackgroundTransparency = 1
Instances.title.Position = UDim2.new(0, 0, 0.359477133, 0)
Instances.title.BorderSizePixel = 0
Instances.title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.title.TextColor3 = Color3.fromRGB(255, 255, 255)
Instances.title.Text = "kitiana 1.0.0 (kitlibr)"
Instances.title.TextSize = 16
Instances.title.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Bold, Enum.FontStyle.Normal)

Instances.description.Name = "description"
Instances.description.Parent = Instances.Frame
Instances.description.Size = UDim2.new(0, 392, 0, 21)
Instances.description.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.description.BackgroundTransparency = 1
Instances.description.Position = UDim2.new(0, 0, 0.86601305, 0)
Instances.description.BorderSizePixel = 0
Instances.description.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.description.TextColor3 = Color3.fromRGB(255, 255, 255)
Instances.description.Text = "thank you for using kitlib :3"
Instances.description.TextSize = 16
Instances.description.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Bold, Enum.FontStyle.Normal)

Instances.UIGradient.Name = "UIGradient"
Instances.UIGradient.Parent = Instances.Frame
Instances.UIGradient.Offset = Vector2.new(1, 0)
Instances.UIGradient.Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 67, 67)), ColorSequenceKeypoint.new(1, Color3.fromRGB(13, 13, 13))})
Instances.UIGradient.Rotation = 104

-- Function "LocalScript"
(function()
	local script = Instance.new("LocalScript", Instances.Frame)
	local TweenService = game:GetService("TweenService")
	
	script.Parent.Position = UDim2.new(0.5, -script.Parent.AbsoluteSize.X/2, 0.5, -script.Parent.AbsoluteSize.Y/2)
	script.Parent.BackgroundTransparency = 1
	script.Parent.title.TextTransparency = 1
	script.Parent.description.TextTransparency = 1
	script.Parent.loadedtext.TextTransparency = 1
	script.Parent.Parent.ResetOnSpawn = false
	-- Function to simplify tween creation and execution
	local function playTween(object, tweenInfo, properties)
		local tween = TweenService:Create(object, tweenInfo, properties)
		tween:Play()
		return tween
	end
	
	playTween(script.Parent.UIGradient, TweenInfo.new(300, Enum.EasingStyle.Quint, Enum.EasingDirection.Out), {Rotation = -129})
	
	-- Start tweens
	playTween(script.Parent, TweenInfo.new(0.5, Enum.EasingStyle.Quint, Enum.EasingDirection.Out), {BackgroundTransparency = 0})
	wait(0.6)
	playTween(script.Parent.loadedtext, TweenInfo.new(0.5, Enum.EasingStyle.Quint, Enum.EasingDirection.Out), {TextTransparency = 0})
	wait(0.6)
	playTween(script.Parent.title, TweenInfo.new(0.5, Enum.EasingStyle.Quint, Enum.EasingDirection.Out), {TextTransparency = 0})
	wait(0.6)
	playTween(script.Parent.description, TweenInfo.new(0.5, Enum.EasingStyle.Quint, Enum.EasingDirection.Out), {TextTransparency = 0})
	
	wait(1)
	
	-- Reverse tweens
	playTween(script.Parent.description, TweenInfo.new(0.5, Enum.EasingStyle.Quint, Enum.EasingDirection.Out), {TextTransparency = 1})
	wait(0.6)
	playTween(script.Parent.title, TweenInfo.new(0.5, Enum.EasingStyle.Quint, Enum.EasingDirection.Out), {TextTransparency = 1})
	wait(0.6)
	playTween(script.Parent.loadedtext, TweenInfo.new(0.5, Enum.EasingStyle.Quint, Enum.EasingDirection.Out), {TextTransparency = 1})
	wait(0.6)
	playTween(script.Parent, TweenInfo.new(0.5, Enum.EasingStyle.Quint, Enum.EasingDirection.Out), {BackgroundTransparency = 1})
	
	wait(1)
	
	script.Parent.Parent.Enabled = false
	
	
end)()

--[[ End of generation. ]]
